/**
 * Mock AI Analysis Generator
 * Generates realistic medical analysis text files as attachments
 */

interface AnalysisResult {
  filename: string;
  content: string;
  type: 'text/plain';
}

const MEDICAL_TEMPLATES = {
  'blood_test': {
    title: 'Blood Test Analysis Report',
    findings: [
      'Complete Blood Count (CBC) shows normal white blood cell count',
      'Hemoglobin levels within normal range (12.5-15.5 g/dL)',
      'Platelet count adequate for normal clotting function',
      'No signs of anemia or infection detected',
      'Liver function tests show normal enzyme levels'
    ],
    recommendations: [
      'Continue current medication regimen',
      'Follow up in 3 months for routine monitoring',
      'Maintain healthy diet and regular exercise',
      'Stay hydrated and get adequate sleep'
    ]
  },
  'xray': {
    title: 'X-Ray Imaging Analysis',
    findings: [
      'No acute fractures or dislocations observed',
      'Bone density appears normal for age group',
      'Joint spaces are well-maintained',
      'No signs of arthritis or degenerative changes',
      'Soft tissue structures appear normal'
    ],
    recommendations: [
      'No immediate treatment required',
      'Continue physical therapy if applicable',
      'Monitor for any changes in symptoms',
      'Return if pain or mobility issues worsen'
    ]
  },
  'general': {
    title: 'General Medical Analysis',
    findings: [
      'Vital signs within normal parameters',
      'No immediate health concerns identified',
      'Patient history reviewed and documented',
      'Current symptoms appear manageable',
      'Overall health status is stable'
    ],
    recommendations: [
      'Continue preventive care measures',
      'Schedule regular check-ups as recommended',
      'Maintain current lifestyle modifications',
      'Contact healthcare provider if symptoms change'
    ]
  }
};

export function generateMockAnalysis(fileName: string, fileType?: string): AnalysisResult {
  // Determine analysis type based on filename or file type
  let templateKey = 'general';
  const lowerFileName = fileName.toLowerCase();
  
  if (lowerFileName.includes('blood') || lowerFileName.includes('lab')) {
    templateKey = 'blood_test';
  } else if (lowerFileName.includes('xray') || lowerFileName.includes('x-ray') || 
             lowerFileName.includes('image') || fileType?.includes('image')) {
    templateKey = 'xray';
  }
  
  const template = MEDICAL_TEMPLATES[templateKey as keyof typeof MEDICAL_TEMPLATES];
  const timestamp = new Date().toLocaleString();
  
  const content = `
${template.title}
Generated: ${timestamp}
Patient File: ${fileName}

ANALYSIS SUMMARY:
================

KEY FINDINGS:
${template.findings.map((finding, i) => `${i + 1}. ${finding}`).join('\n')}

RECOMMENDATIONS:
${template.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

ADDITIONAL NOTES:
- This analysis was generated using AI-powered medical assessment tools
- Results should be reviewed by a qualified healthcare professional
- Follow up with your healthcare provider for any concerns
- Keep this report for your medical records

DISCLAIMER:
This AI-generated analysis is for informational purposes only and should not replace professional medical advice, diagnosis, or treatment.

---
Generated by MediVet AI Analysis System
Report ID: AI-${Date.now()}
`;

  return {
    filename: `AI_Analysis_${fileName.replace(/\.[^/.]+$/, '')}_${Date.now()}.txt`,
    content: content.trim(),
    type: 'text/plain'
  };
}

export function createAnalysisFile(analysis: AnalysisResult): File {
  const blob = new Blob([analysis.content], { type: analysis.type });
  return new File([blob], analysis.filename, { type: analysis.type });
}
